### ISSUE TITLE
Docs on how to run? :)

### ISSUE THREAD

**Issue by mario** [dlucian/invoicer#1]
Would be helpful.

**Comment by dlucian** [comment]
@mario - no installation guide so far, but if you're not in a big hurry, I can provide one next week.

**Comment by mario** [comment]
I would appreciate it very much @dlucian

**Comment by mario** [comment]
Any progress on this maybe?

**Comment by dlucian** [comment]
@mario - I'm assuming a deployment tutorial on DigitalOcean would work for you?

**Comment by mario** [comment]
@dlucian anything would, yes - I'm fairly confident with sysadmin, but not so much with Laravel yet and the setup you have going on here, so I want to make sure I don't miss anything :)

**Comment by mario** [comment]
@dlucian just wondering if you've managed to do anything regarding this?

**Comment by dlucian** [comment]
Sorry @mario, I've been slammed with work these couple of weeks. Might not be able to put that together until early next week.

**Comment by dlucian** [comment]
It's been 2 years but @itech-ro added docs on how to run using Docker in the README.
